name: ProTools
version: Release 1.1
website: https://github.com/ProCrafters/ProTools
author: TheMolkaPL
description: Plugin stworzony specjalnie dla ProCrafters!

main: pl.themolka.protools.ProTools

commands:
    protools:
        description: Komendy pluginu ProTools
        usage: /protools <about|border>
    pt:
        description: Komendy pluginu ProTools
        usage: /pt <about|border>